### ISSUE TITLE
save() 405 method not allowed

### ISSUE THREAD

**Issue by j0hnsmith** [blacklocus/angular-django-rest-resource#10]
If I use the example in the readme I get `405 (METHOD NOT ALLOWED)` when I call `myPoll.save()`. This is kind of expected as DRF doesn't (by default) allow POST requests to an instance, instead it wants a PUT request for model updates. Here's my solution

```
var Poll = djResource('/polls/:pollId/', {pollId:'@id'}, 
    {
        'update': 'PUT'
    }
);

var myPoll = Poll.get({pollId:86}, function() {
    myPoll.readByUser = true;
    //myPoll.$save();  // 405 METHOD NOT ALLOWED
    myPoll.$update();  // works
});
```

The update method can be automatically added [here](https://github.com/blacklocus/angular-django-rest-resource/blob/master/angular-django-rest-resource.js#L146) to always make it available, I'd send a pull request but it doesn't seem worth it for a one line change.

**Comment by JustinTArthur** [comment]
`POST`s should be allowed just fine, at least in the DRF versions I'm testing against. Can you tell me what decorators you're using around your views and which view class(es) you're using? Thanks!

**Comment by shayh** [comment]
having the same problem, my object is Issue.

``` python
class IssueSerializer(serializers.ModelSerializer):
    class Meta:
        model = Issue
        read_only_fields = ('typ', 'sub_id', 'psnt', 'site', 'closed')

class IssueView(viewsets.ModelViewSet):
    model = Issue
    serializer_class = IssueSerializer
```

``` javascript
.factory('Issues', ['djResource', function(djResource) {
      return djResource('/api/issues_tracker/issues/:issueId/', {issueId: '@id'});
}])


$scope.updateIssue = function(data) {
        this.issue.description = data
        return this.issue.$save();
};
```

server returns:
POST http://myserver:8000/api/issues_tracker/issues/1/ 405 (METHOD NOT ALLOWED)

**Comment by JustinTArthur** [comment]
Ahh, OK, thanks for your example, @shayh and for the workaround, @j0hnsmith.

I assume you're using the [DefaultRouter](http://www.django-rest-framework.org/api-guide/routers#defaultrouter) to bind the viewset to URLs or something with a similar pattern? This is not a case I had available originally, and didn't realize the detail view would drop `POST` support.

**Comment by JustinTArthur** [comment]
Sorry it took a while. I've done two things:
- I've added an `update` action that employs `PUT` to the default action set.
- If the default `save` action is used and the `id` field is set on instance, `PUT` is used instead of `POST`. If you use `ModelSerializer` and the usual primary key nomenclature of _id_, then this will satisfy. To use a different field as an indicator of object pre-existence, an overriding `save` action should be created with a different `method_if_field_has_value` like this:
  
  ```
  var Poll = djResource('/polls/:pollId/', {pollId:'@id'}, 
  {
      // If the poll has a poll_locator, we're updating an existing poll.
      'save': {method: 'POST', method_if_field_has_value: ['poll_locator', 'PUT']}
  });
  ```
