### ISSUE TITLE
Last page of paginated request

### ISSUE THREAD

**Issue by evdoks** [blacklocus/angular-django-rest-resource#8]
Is there is a way to determine when the last request of a series of paginated requests is completed? I need to make a function call that processes the complete result set of the request but cannot figure out a nice way for determining when the promise object contains all the paginated data.

**Comment by evdoks** [comment]
Found a solution: just use `success` callback, which is called after all pages are loaded.

**Comment by JustinTArthur** [comment]
Yep! That's the right approach.
